import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Main from "@/components/Main";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Main>
                    <Navbar />
                    <div className="grid grid-cols-12 justify-center">
                        <main className="px-12 py-4 lg:col-start-3 lg:col-span-8 md:col-start-2 md:col-span-10 col-span-12">
                            {children}
                        </main>
                    </div>
                </Main>
            </body>
        </html>
    );
}
